/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 29
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_upper_ident = 1,
  anon_sym_COLON = 2,
  anon_sym_I8 = 3,
  anon_sym_U8 = 4,
  anon_sym_I16 = 5,
  anon_sym_U16 = 6,
  anon_sym_I32 = 7,
  anon_sym_U32 = 8,
  anon_sym_I64 = 9,
  anon_sym_U64 = 10,
  anon_sym_I128 = 11,
  anon_sym_U128 = 12,
  anon_sym_F32 = 13,
  anon_sym_F64 = 14,
  anon_sym_Str = 15,
  anon_sym_Bool = 16,
  anon_sym_List = 17,
  anon_sym_Map = 18,
  anon_sym_LBRACE = 19,
  anon_sym_COMMA = 20,
  anon_sym_RBRACE = 21,
  anon_sym_QMARK = 22,
  anon_sym_LBRACK = 23,
  anon_sym_RBRACK = 24,
  sym_open_modifier = 25,
  sym_lower_ident = 26,
  sym_schema = 27,
  sym_type_definition = 28,
  sym__type = 29,
  sym_primitive_type = 30,
  sym_list_type = 31,
  sym_map_type = 32,
  sym_record_type = 33,
  sym_record_field = 34,
  sym_tag_union = 35,
  sym_tag_variant = 36,
  sym_type_reference = 37,
  aux_sym_schema_repeat1 = 38,
  aux_sym_record_type_repeat1 = 39,
  aux_sym_tag_union_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_upper_ident] = "upper_ident",
  [anon_sym_COLON] = ":",
  [anon_sym_I8] = "I8",
  [anon_sym_U8] = "U8",
  [anon_sym_I16] = "I16",
  [anon_sym_U16] = "U16",
  [anon_sym_I32] = "I32",
  [anon_sym_U32] = "U32",
  [anon_sym_I64] = "I64",
  [anon_sym_U64] = "U64",
  [anon_sym_I128] = "I128",
  [anon_sym_U128] = "U128",
  [anon_sym_F32] = "F32",
  [anon_sym_F64] = "F64",
  [anon_sym_Str] = "Str",
  [anon_sym_Bool] = "Bool",
  [anon_sym_List] = "List",
  [anon_sym_Map] = "Map",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_QMARK] = "\?",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_open_modifier] = "open_modifier",
  [sym_lower_ident] = "lower_ident",
  [sym_schema] = "schema",
  [sym_type_definition] = "type_definition",
  [sym__type] = "_type",
  [sym_primitive_type] = "primitive_type",
  [sym_list_type] = "list_type",
  [sym_map_type] = "map_type",
  [sym_record_type] = "record_type",
  [sym_record_field] = "record_field",
  [sym_tag_union] = "tag_union",
  [sym_tag_variant] = "tag_variant",
  [sym_type_reference] = "type_reference",
  [aux_sym_schema_repeat1] = "schema_repeat1",
  [aux_sym_record_type_repeat1] = "record_type_repeat1",
  [aux_sym_tag_union_repeat1] = "tag_union_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_upper_ident] = sym_upper_ident,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_I8] = anon_sym_I8,
  [anon_sym_U8] = anon_sym_U8,
  [anon_sym_I16] = anon_sym_I16,
  [anon_sym_U16] = anon_sym_U16,
  [anon_sym_I32] = anon_sym_I32,
  [anon_sym_U32] = anon_sym_U32,
  [anon_sym_I64] = anon_sym_I64,
  [anon_sym_U64] = anon_sym_U64,
  [anon_sym_I128] = anon_sym_I128,
  [anon_sym_U128] = anon_sym_U128,
  [anon_sym_F32] = anon_sym_F32,
  [anon_sym_F64] = anon_sym_F64,
  [anon_sym_Str] = anon_sym_Str,
  [anon_sym_Bool] = anon_sym_Bool,
  [anon_sym_List] = anon_sym_List,
  [anon_sym_Map] = anon_sym_Map,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_open_modifier] = sym_open_modifier,
  [sym_lower_ident] = sym_lower_ident,
  [sym_schema] = sym_schema,
  [sym_type_definition] = sym_type_definition,
  [sym__type] = sym__type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_list_type] = sym_list_type,
  [sym_map_type] = sym_map_type,
  [sym_record_type] = sym_record_type,
  [sym_record_field] = sym_record_field,
  [sym_tag_union] = sym_tag_union,
  [sym_tag_variant] = sym_tag_variant,
  [sym_type_reference] = sym_type_reference,
  [aux_sym_schema_repeat1] = aux_sym_schema_repeat1,
  [aux_sym_record_type_repeat1] = aux_sym_record_type_repeat1,
  [aux_sym_tag_union_repeat1] = aux_sym_tag_union_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_upper_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_U8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_U16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_U32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_U64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_U128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_List] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Map] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_open_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_lower_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_map_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_field] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_union] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_type_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_schema_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_union_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_element = 1,
  field_key = 2,
  field_name = 3,
  field_payload = 4,
  field_type = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_element] = "element",
  [field_key] = "key",
  [field_name] = "name",
  [field_payload] = "payload",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_type, 2},
  [2] =
    {field_element, 1},
  [3] =
    {field_name, 0},
  [4] =
    {field_key, 1},
    {field_value, 2},
  [6] =
    {field_name, 0},
    {field_payload, 1},
  [8] =
    {field_name, 0},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      ADVANCE_MAP(
        '*', 9,
        ',', 4,
        ':', 2,
        '?', 6,
        '[', 7,
        ']', 8,
        '{', 3,
        '}', 5,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(10);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_open_modifier);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_upper_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_lower_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'B') ADVANCE(1);
      if (lookahead == 'F') ADVANCE(2);
      if (lookahead == 'I') ADVANCE(3);
      if (lookahead == 'L') ADVANCE(4);
      if (lookahead == 'M') ADVANCE(5);
      if (lookahead == 'S') ADVANCE(6);
      if (lookahead == 'U') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '3') ADVANCE(9);
      if (lookahead == '6') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == '1') ADVANCE(11);
      if (lookahead == '3') ADVANCE(12);
      if (lookahead == '6') ADVANCE(13);
      if (lookahead == '8') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '1') ADVANCE(18);
      if (lookahead == '3') ADVANCE(19);
      if (lookahead == '6') ADVANCE(20);
      if (lookahead == '8') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == '2') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == '4') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == '2') ADVANCE(25);
      if (lookahead == '6') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == '2') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == '4') ADVANCE(28);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_I8);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == '2') ADVANCE(32);
      if (lookahead == '6') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == '2') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == '4') ADVANCE(35);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_U8);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_F32);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_F64);
      END_STATE();
    case 25:
      if (lookahead == '8') ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_I16);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_I32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_I64);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_Map);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_Str);
      END_STATE();
    case 32:
      if (lookahead == '8') ADVANCE(39);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_U16);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_U32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_U64);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_Bool);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_I128);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_List);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_U128);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_upper_ident] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_I8] = ACTIONS(1),
    [anon_sym_U8] = ACTIONS(1),
    [anon_sym_I16] = ACTIONS(1),
    [anon_sym_U16] = ACTIONS(1),
    [anon_sym_I32] = ACTIONS(1),
    [anon_sym_U32] = ACTIONS(1),
    [anon_sym_I64] = ACTIONS(1),
    [anon_sym_U64] = ACTIONS(1),
    [anon_sym_I128] = ACTIONS(1),
    [anon_sym_U128] = ACTIONS(1),
    [anon_sym_F32] = ACTIONS(1),
    [anon_sym_F64] = ACTIONS(1),
    [anon_sym_Str] = ACTIONS(1),
    [anon_sym_Bool] = ACTIONS(1),
    [anon_sym_List] = ACTIONS(1),
    [anon_sym_Map] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_open_modifier] = ACTIONS(1),
    [sym_lower_ident] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_schema] = STATE(53),
    [sym_type_definition] = STATE(30),
    [aux_sym_schema_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_upper_ident] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__type] = STATE(51),
    [sym_primitive_type] = STATE(51),
    [sym_list_type] = STATE(51),
    [sym_map_type] = STATE(51),
    [sym_record_type] = STATE(51),
    [sym_tag_union] = STATE(51),
    [sym_type_reference] = STATE(51),
    [sym_upper_ident] = ACTIONS(7),
    [anon_sym_I8] = ACTIONS(9),
    [anon_sym_U8] = ACTIONS(9),
    [anon_sym_I16] = ACTIONS(9),
    [anon_sym_U16] = ACTIONS(9),
    [anon_sym_I32] = ACTIONS(9),
    [anon_sym_U32] = ACTIONS(9),
    [anon_sym_I64] = ACTIONS(9),
    [anon_sym_U64] = ACTIONS(9),
    [anon_sym_I128] = ACTIONS(9),
    [anon_sym_U128] = ACTIONS(9),
    [anon_sym_F32] = ACTIONS(9),
    [anon_sym_F64] = ACTIONS(9),
    [anon_sym_Str] = ACTIONS(9),
    [anon_sym_Bool] = ACTIONS(9),
    [anon_sym_List] = ACTIONS(11),
    [anon_sym_Map] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_RBRACK] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym__type] = STATE(43),
    [sym_primitive_type] = STATE(43),
    [sym_list_type] = STATE(43),
    [sym_map_type] = STATE(43),
    [sym_record_type] = STATE(43),
    [sym_tag_union] = STATE(43),
    [sym_type_reference] = STATE(43),
    [sym_upper_ident] = ACTIONS(7),
    [anon_sym_I8] = ACTIONS(9),
    [anon_sym_U8] = ACTIONS(9),
    [anon_sym_I16] = ACTIONS(9),
    [anon_sym_U16] = ACTIONS(9),
    [anon_sym_I32] = ACTIONS(9),
    [anon_sym_U32] = ACTIONS(9),
    [anon_sym_I64] = ACTIONS(9),
    [anon_sym_U64] = ACTIONS(9),
    [anon_sym_I128] = ACTIONS(9),
    [anon_sym_U128] = ACTIONS(9),
    [anon_sym_F32] = ACTIONS(9),
    [anon_sym_F64] = ACTIONS(9),
    [anon_sym_Str] = ACTIONS(9),
    [anon_sym_Bool] = ACTIONS(9),
    [anon_sym_List] = ACTIONS(11),
    [anon_sym_Map] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym__type] = STATE(44),
    [sym_primitive_type] = STATE(44),
    [sym_list_type] = STATE(44),
    [sym_map_type] = STATE(44),
    [sym_record_type] = STATE(44),
    [sym_tag_union] = STATE(44),
    [sym_type_reference] = STATE(44),
    [sym_upper_ident] = ACTIONS(7),
    [anon_sym_I8] = ACTIONS(9),
    [anon_sym_U8] = ACTIONS(9),
    [anon_sym_I16] = ACTIONS(9),
    [anon_sym_U16] = ACTIONS(9),
    [anon_sym_I32] = ACTIONS(9),
    [anon_sym_U32] = ACTIONS(9),
    [anon_sym_I64] = ACTIONS(9),
    [anon_sym_U64] = ACTIONS(9),
    [anon_sym_I128] = ACTIONS(9),
    [anon_sym_U128] = ACTIONS(9),
    [anon_sym_F32] = ACTIONS(9),
    [anon_sym_F64] = ACTIONS(9),
    [anon_sym_Str] = ACTIONS(9),
    [anon_sym_Bool] = ACTIONS(9),
    [anon_sym_List] = ACTIONS(11),
    [anon_sym_Map] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(5)] = {
    [sym__type] = STATE(21),
    [sym_primitive_type] = STATE(21),
    [sym_list_type] = STATE(21),
    [sym_map_type] = STATE(21),
    [sym_record_type] = STATE(21),
    [sym_tag_union] = STATE(21),
    [sym_type_reference] = STATE(21),
    [sym_upper_ident] = ACTIONS(7),
    [anon_sym_I8] = ACTIONS(9),
    [anon_sym_U8] = ACTIONS(9),
    [anon_sym_I16] = ACTIONS(9),
    [anon_sym_U16] = ACTIONS(9),
    [anon_sym_I32] = ACTIONS(9),
    [anon_sym_U32] = ACTIONS(9),
    [anon_sym_I64] = ACTIONS(9),
    [anon_sym_U64] = ACTIONS(9),
    [anon_sym_I128] = ACTIONS(9),
    [anon_sym_U128] = ACTIONS(9),
    [anon_sym_F32] = ACTIONS(9),
    [anon_sym_F64] = ACTIONS(9),
    [anon_sym_Str] = ACTIONS(9),
    [anon_sym_Bool] = ACTIONS(9),
    [anon_sym_List] = ACTIONS(11),
    [anon_sym_Map] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym__type] = STATE(7),
    [sym_primitive_type] = STATE(7),
    [sym_list_type] = STATE(7),
    [sym_map_type] = STATE(7),
    [sym_record_type] = STATE(7),
    [sym_tag_union] = STATE(7),
    [sym_type_reference] = STATE(7),
    [sym_upper_ident] = ACTIONS(7),
    [anon_sym_I8] = ACTIONS(9),
    [anon_sym_U8] = ACTIONS(9),
    [anon_sym_I16] = ACTIONS(9),
    [anon_sym_U16] = ACTIONS(9),
    [anon_sym_I32] = ACTIONS(9),
    [anon_sym_U32] = ACTIONS(9),
    [anon_sym_I64] = ACTIONS(9),
    [anon_sym_U64] = ACTIONS(9),
    [anon_sym_I128] = ACTIONS(9),
    [anon_sym_U128] = ACTIONS(9),
    [anon_sym_F32] = ACTIONS(9),
    [anon_sym_F64] = ACTIONS(9),
    [anon_sym_Str] = ACTIONS(9),
    [anon_sym_Bool] = ACTIONS(9),
    [anon_sym_List] = ACTIONS(11),
    [anon_sym_Map] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(7)] = {
    [sym__type] = STATE(18),
    [sym_primitive_type] = STATE(18),
    [sym_list_type] = STATE(18),
    [sym_map_type] = STATE(18),
    [sym_record_type] = STATE(18),
    [sym_tag_union] = STATE(18),
    [sym_type_reference] = STATE(18),
    [sym_upper_ident] = ACTIONS(7),
    [anon_sym_I8] = ACTIONS(9),
    [anon_sym_U8] = ACTIONS(9),
    [anon_sym_I16] = ACTIONS(9),
    [anon_sym_U16] = ACTIONS(9),
    [anon_sym_I32] = ACTIONS(9),
    [anon_sym_U32] = ACTIONS(9),
    [anon_sym_I64] = ACTIONS(9),
    [anon_sym_U64] = ACTIONS(9),
    [anon_sym_I128] = ACTIONS(9),
    [anon_sym_U128] = ACTIONS(9),
    [anon_sym_F32] = ACTIONS(9),
    [anon_sym_F64] = ACTIONS(9),
    [anon_sym_Str] = ACTIONS(9),
    [anon_sym_Bool] = ACTIONS(9),
    [anon_sym_List] = ACTIONS(11),
    [anon_sym_Map] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(8)] = {
    [sym__type] = STATE(49),
    [sym_primitive_type] = STATE(49),
    [sym_list_type] = STATE(49),
    [sym_map_type] = STATE(49),
    [sym_record_type] = STATE(49),
    [sym_tag_union] = STATE(49),
    [sym_type_reference] = STATE(49),
    [sym_upper_ident] = ACTIONS(7),
    [anon_sym_I8] = ACTIONS(9),
    [anon_sym_U8] = ACTIONS(9),
    [anon_sym_I16] = ACTIONS(9),
    [anon_sym_U16] = ACTIONS(9),
    [anon_sym_I32] = ACTIONS(9),
    [anon_sym_U32] = ACTIONS(9),
    [anon_sym_I64] = ACTIONS(9),
    [anon_sym_U64] = ACTIONS(9),
    [anon_sym_I128] = ACTIONS(9),
    [anon_sym_U128] = ACTIONS(9),
    [anon_sym_F32] = ACTIONS(9),
    [anon_sym_F64] = ACTIONS(9),
    [anon_sym_Str] = ACTIONS(9),
    [anon_sym_Bool] = ACTIONS(9),
    [anon_sym_List] = ACTIONS(11),
    [anon_sym_Map] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_upper_ident] = ACTIONS(23),
    [anon_sym_I8] = ACTIONS(23),
    [anon_sym_U8] = ACTIONS(23),
    [anon_sym_I16] = ACTIONS(23),
    [anon_sym_U16] = ACTIONS(23),
    [anon_sym_I32] = ACTIONS(23),
    [anon_sym_U32] = ACTIONS(23),
    [anon_sym_I64] = ACTIONS(23),
    [anon_sym_U64] = ACTIONS(23),
    [anon_sym_I128] = ACTIONS(23),
    [anon_sym_U128] = ACTIONS(23),
    [anon_sym_F32] = ACTIONS(23),
    [anon_sym_F64] = ACTIONS(23),
    [anon_sym_Str] = ACTIONS(23),
    [anon_sym_Bool] = ACTIONS(23),
    [anon_sym_List] = ACTIONS(23),
    [anon_sym_Map] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [sym_open_modifier] = ACTIONS(25),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_upper_ident] = ACTIONS(29),
    [anon_sym_I8] = ACTIONS(29),
    [anon_sym_U8] = ACTIONS(29),
    [anon_sym_I16] = ACTIONS(29),
    [anon_sym_U16] = ACTIONS(29),
    [anon_sym_I32] = ACTIONS(29),
    [anon_sym_U32] = ACTIONS(29),
    [anon_sym_I64] = ACTIONS(29),
    [anon_sym_U64] = ACTIONS(29),
    [anon_sym_I128] = ACTIONS(29),
    [anon_sym_U128] = ACTIONS(29),
    [anon_sym_F32] = ACTIONS(29),
    [anon_sym_F64] = ACTIONS(29),
    [anon_sym_Str] = ACTIONS(29),
    [anon_sym_Bool] = ACTIONS(29),
    [anon_sym_List] = ACTIONS(29),
    [anon_sym_Map] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [sym_open_modifier] = ACTIONS(31),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_upper_ident] = ACTIONS(35),
    [anon_sym_I8] = ACTIONS(35),
    [anon_sym_U8] = ACTIONS(35),
    [anon_sym_I16] = ACTIONS(35),
    [anon_sym_U16] = ACTIONS(35),
    [anon_sym_I32] = ACTIONS(35),
    [anon_sym_U32] = ACTIONS(35),
    [anon_sym_I64] = ACTIONS(35),
    [anon_sym_U64] = ACTIONS(35),
    [anon_sym_I128] = ACTIONS(35),
    [anon_sym_U128] = ACTIONS(35),
    [anon_sym_F32] = ACTIONS(35),
    [anon_sym_F64] = ACTIONS(35),
    [anon_sym_Str] = ACTIONS(35),
    [anon_sym_Bool] = ACTIONS(35),
    [anon_sym_List] = ACTIONS(35),
    [anon_sym_Map] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(33),
    [sym_open_modifier] = ACTIONS(37),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_upper_ident] = ACTIONS(41),
    [anon_sym_I8] = ACTIONS(41),
    [anon_sym_U8] = ACTIONS(41),
    [anon_sym_I16] = ACTIONS(41),
    [anon_sym_U16] = ACTIONS(41),
    [anon_sym_I32] = ACTIONS(41),
    [anon_sym_U32] = ACTIONS(41),
    [anon_sym_I64] = ACTIONS(41),
    [anon_sym_U64] = ACTIONS(41),
    [anon_sym_I128] = ACTIONS(41),
    [anon_sym_U128] = ACTIONS(41),
    [anon_sym_F32] = ACTIONS(41),
    [anon_sym_F64] = ACTIONS(41),
    [anon_sym_Str] = ACTIONS(41),
    [anon_sym_Bool] = ACTIONS(41),
    [anon_sym_List] = ACTIONS(41),
    [anon_sym_Map] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(39),
    [sym_open_modifier] = ACTIONS(43),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_upper_ident] = ACTIONS(47),
    [anon_sym_I8] = ACTIONS(47),
    [anon_sym_U8] = ACTIONS(47),
    [anon_sym_I16] = ACTIONS(47),
    [anon_sym_U16] = ACTIONS(47),
    [anon_sym_I32] = ACTIONS(47),
    [anon_sym_U32] = ACTIONS(47),
    [anon_sym_I64] = ACTIONS(47),
    [anon_sym_U64] = ACTIONS(47),
    [anon_sym_I128] = ACTIONS(47),
    [anon_sym_U128] = ACTIONS(47),
    [anon_sym_F32] = ACTIONS(47),
    [anon_sym_F64] = ACTIONS(47),
    [anon_sym_Str] = ACTIONS(47),
    [anon_sym_Bool] = ACTIONS(47),
    [anon_sym_List] = ACTIONS(47),
    [anon_sym_Map] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(45),
    [anon_sym_COMMA] = ACTIONS(45),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(45),
    [sym_open_modifier] = ACTIONS(49),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_upper_ident] = ACTIONS(53),
    [anon_sym_I8] = ACTIONS(53),
    [anon_sym_U8] = ACTIONS(53),
    [anon_sym_I16] = ACTIONS(53),
    [anon_sym_U16] = ACTIONS(53),
    [anon_sym_I32] = ACTIONS(53),
    [anon_sym_U32] = ACTIONS(53),
    [anon_sym_I64] = ACTIONS(53),
    [anon_sym_U64] = ACTIONS(53),
    [anon_sym_I128] = ACTIONS(53),
    [anon_sym_U128] = ACTIONS(53),
    [anon_sym_F32] = ACTIONS(53),
    [anon_sym_F64] = ACTIONS(53),
    [anon_sym_Str] = ACTIONS(53),
    [anon_sym_Bool] = ACTIONS(53),
    [anon_sym_List] = ACTIONS(53),
    [anon_sym_Map] = ACTIONS(53),
    [anon_sym_LBRACE] = ACTIONS(51),
    [anon_sym_COMMA] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_RBRACK] = ACTIONS(51),
    [sym_open_modifier] = ACTIONS(55),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_upper_ident] = ACTIONS(59),
    [anon_sym_I8] = ACTIONS(59),
    [anon_sym_U8] = ACTIONS(59),
    [anon_sym_I16] = ACTIONS(59),
    [anon_sym_U16] = ACTIONS(59),
    [anon_sym_I32] = ACTIONS(59),
    [anon_sym_U32] = ACTIONS(59),
    [anon_sym_I64] = ACTIONS(59),
    [anon_sym_U64] = ACTIONS(59),
    [anon_sym_I128] = ACTIONS(59),
    [anon_sym_U128] = ACTIONS(59),
    [anon_sym_F32] = ACTIONS(59),
    [anon_sym_F64] = ACTIONS(59),
    [anon_sym_Str] = ACTIONS(59),
    [anon_sym_Bool] = ACTIONS(59),
    [anon_sym_List] = ACTIONS(59),
    [anon_sym_Map] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_COMMA] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_RBRACK] = ACTIONS(57),
    [sym_open_modifier] = ACTIONS(61),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_upper_ident] = ACTIONS(65),
    [anon_sym_I8] = ACTIONS(65),
    [anon_sym_U8] = ACTIONS(65),
    [anon_sym_I16] = ACTIONS(65),
    [anon_sym_U16] = ACTIONS(65),
    [anon_sym_I32] = ACTIONS(65),
    [anon_sym_U32] = ACTIONS(65),
    [anon_sym_I64] = ACTIONS(65),
    [anon_sym_U64] = ACTIONS(65),
    [anon_sym_I128] = ACTIONS(65),
    [anon_sym_U128] = ACTIONS(65),
    [anon_sym_F32] = ACTIONS(65),
    [anon_sym_F64] = ACTIONS(65),
    [anon_sym_Str] = ACTIONS(65),
    [anon_sym_Bool] = ACTIONS(65),
    [anon_sym_List] = ACTIONS(65),
    [anon_sym_Map] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_COMMA] = ACTIONS(63),
    [anon_sym_RBRACE] = ACTIONS(63),
    [anon_sym_LBRACK] = ACTIONS(63),
    [anon_sym_RBRACK] = ACTIONS(63),
    [sym_open_modifier] = ACTIONS(67),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_upper_ident] = ACTIONS(71),
    [anon_sym_I8] = ACTIONS(71),
    [anon_sym_U8] = ACTIONS(71),
    [anon_sym_I16] = ACTIONS(71),
    [anon_sym_U16] = ACTIONS(71),
    [anon_sym_I32] = ACTIONS(71),
    [anon_sym_U32] = ACTIONS(71),
    [anon_sym_I64] = ACTIONS(71),
    [anon_sym_U64] = ACTIONS(71),
    [anon_sym_I128] = ACTIONS(71),
    [anon_sym_U128] = ACTIONS(71),
    [anon_sym_F32] = ACTIONS(71),
    [anon_sym_F64] = ACTIONS(71),
    [anon_sym_Str] = ACTIONS(71),
    [anon_sym_Bool] = ACTIONS(71),
    [anon_sym_List] = ACTIONS(71),
    [anon_sym_Map] = ACTIONS(71),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_COMMA] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(69),
    [anon_sym_RBRACK] = ACTIONS(69),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_upper_ident] = ACTIONS(75),
    [anon_sym_I8] = ACTIONS(75),
    [anon_sym_U8] = ACTIONS(75),
    [anon_sym_I16] = ACTIONS(75),
    [anon_sym_U16] = ACTIONS(75),
    [anon_sym_I32] = ACTIONS(75),
    [anon_sym_U32] = ACTIONS(75),
    [anon_sym_I64] = ACTIONS(75),
    [anon_sym_U64] = ACTIONS(75),
    [anon_sym_I128] = ACTIONS(75),
    [anon_sym_U128] = ACTIONS(75),
    [anon_sym_F32] = ACTIONS(75),
    [anon_sym_F64] = ACTIONS(75),
    [anon_sym_Str] = ACTIONS(75),
    [anon_sym_Bool] = ACTIONS(75),
    [anon_sym_List] = ACTIONS(75),
    [anon_sym_Map] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_COMMA] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(73),
    [anon_sym_RBRACK] = ACTIONS(73),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym_upper_ident] = ACTIONS(79),
    [anon_sym_I8] = ACTIONS(79),
    [anon_sym_U8] = ACTIONS(79),
    [anon_sym_I16] = ACTIONS(79),
    [anon_sym_U16] = ACTIONS(79),
    [anon_sym_I32] = ACTIONS(79),
    [anon_sym_U32] = ACTIONS(79),
    [anon_sym_I64] = ACTIONS(79),
    [anon_sym_U64] = ACTIONS(79),
    [anon_sym_I128] = ACTIONS(79),
    [anon_sym_U128] = ACTIONS(79),
    [anon_sym_F32] = ACTIONS(79),
    [anon_sym_F64] = ACTIONS(79),
    [anon_sym_Str] = ACTIONS(79),
    [anon_sym_Bool] = ACTIONS(79),
    [anon_sym_List] = ACTIONS(79),
    [anon_sym_Map] = ACTIONS(79),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_COMMA] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(77),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_upper_ident] = ACTIONS(35),
    [anon_sym_I8] = ACTIONS(35),
    [anon_sym_U8] = ACTIONS(35),
    [anon_sym_I16] = ACTIONS(35),
    [anon_sym_U16] = ACTIONS(35),
    [anon_sym_I32] = ACTIONS(35),
    [anon_sym_U32] = ACTIONS(35),
    [anon_sym_I64] = ACTIONS(35),
    [anon_sym_U64] = ACTIONS(35),
    [anon_sym_I128] = ACTIONS(35),
    [anon_sym_U128] = ACTIONS(35),
    [anon_sym_F32] = ACTIONS(35),
    [anon_sym_F64] = ACTIONS(35),
    [anon_sym_Str] = ACTIONS(35),
    [anon_sym_Bool] = ACTIONS(35),
    [anon_sym_List] = ACTIONS(35),
    [anon_sym_Map] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(33),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_upper_ident] = ACTIONS(83),
    [anon_sym_I8] = ACTIONS(83),
    [anon_sym_U8] = ACTIONS(83),
    [anon_sym_I16] = ACTIONS(83),
    [anon_sym_U16] = ACTIONS(83),
    [anon_sym_I32] = ACTIONS(83),
    [anon_sym_U32] = ACTIONS(83),
    [anon_sym_I64] = ACTIONS(83),
    [anon_sym_U64] = ACTIONS(83),
    [anon_sym_I128] = ACTIONS(83),
    [anon_sym_U128] = ACTIONS(83),
    [anon_sym_F32] = ACTIONS(83),
    [anon_sym_F64] = ACTIONS(83),
    [anon_sym_Str] = ACTIONS(83),
    [anon_sym_Bool] = ACTIONS(83),
    [anon_sym_List] = ACTIONS(83),
    [anon_sym_Map] = ACTIONS(83),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_COMMA] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_upper_ident] = ACTIONS(53),
    [anon_sym_I8] = ACTIONS(53),
    [anon_sym_U8] = ACTIONS(53),
    [anon_sym_I16] = ACTIONS(53),
    [anon_sym_U16] = ACTIONS(53),
    [anon_sym_I32] = ACTIONS(53),
    [anon_sym_U32] = ACTIONS(53),
    [anon_sym_I64] = ACTIONS(53),
    [anon_sym_U64] = ACTIONS(53),
    [anon_sym_I128] = ACTIONS(53),
    [anon_sym_U128] = ACTIONS(53),
    [anon_sym_F32] = ACTIONS(53),
    [anon_sym_F64] = ACTIONS(53),
    [anon_sym_Str] = ACTIONS(53),
    [anon_sym_Bool] = ACTIONS(53),
    [anon_sym_List] = ACTIONS(53),
    [anon_sym_Map] = ACTIONS(53),
    [anon_sym_LBRACE] = ACTIONS(51),
    [anon_sym_COMMA] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_RBRACK] = ACTIONS(51),
  },
  [STATE(23)] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_upper_ident] = ACTIONS(87),
    [anon_sym_I8] = ACTIONS(87),
    [anon_sym_U8] = ACTIONS(87),
    [anon_sym_I16] = ACTIONS(87),
    [anon_sym_U16] = ACTIONS(87),
    [anon_sym_I32] = ACTIONS(87),
    [anon_sym_U32] = ACTIONS(87),
    [anon_sym_I64] = ACTIONS(87),
    [anon_sym_U64] = ACTIONS(87),
    [anon_sym_I128] = ACTIONS(87),
    [anon_sym_U128] = ACTIONS(87),
    [anon_sym_F32] = ACTIONS(87),
    [anon_sym_F64] = ACTIONS(87),
    [anon_sym_Str] = ACTIONS(87),
    [anon_sym_Bool] = ACTIONS(87),
    [anon_sym_List] = ACTIONS(87),
    [anon_sym_Map] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_COMMA] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(85),
    [anon_sym_RBRACK] = ACTIONS(85),
  },
  [STATE(24)] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_upper_ident] = ACTIONS(59),
    [anon_sym_I8] = ACTIONS(59),
    [anon_sym_U8] = ACTIONS(59),
    [anon_sym_I16] = ACTIONS(59),
    [anon_sym_U16] = ACTIONS(59),
    [anon_sym_I32] = ACTIONS(59),
    [anon_sym_U32] = ACTIONS(59),
    [anon_sym_I64] = ACTIONS(59),
    [anon_sym_U64] = ACTIONS(59),
    [anon_sym_I128] = ACTIONS(59),
    [anon_sym_U128] = ACTIONS(59),
    [anon_sym_F32] = ACTIONS(59),
    [anon_sym_F64] = ACTIONS(59),
    [anon_sym_Str] = ACTIONS(59),
    [anon_sym_Bool] = ACTIONS(59),
    [anon_sym_List] = ACTIONS(59),
    [anon_sym_Map] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_COMMA] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_RBRACK] = ACTIONS(57),
  },
  [STATE(25)] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_upper_ident] = ACTIONS(47),
    [anon_sym_I8] = ACTIONS(47),
    [anon_sym_U8] = ACTIONS(47),
    [anon_sym_I16] = ACTIONS(47),
    [anon_sym_U16] = ACTIONS(47),
    [anon_sym_I32] = ACTIONS(47),
    [anon_sym_U32] = ACTIONS(47),
    [anon_sym_I64] = ACTIONS(47),
    [anon_sym_U64] = ACTIONS(47),
    [anon_sym_I128] = ACTIONS(47),
    [anon_sym_U128] = ACTIONS(47),
    [anon_sym_F32] = ACTIONS(47),
    [anon_sym_F64] = ACTIONS(47),
    [anon_sym_Str] = ACTIONS(47),
    [anon_sym_Bool] = ACTIONS(47),
    [anon_sym_List] = ACTIONS(47),
    [anon_sym_Map] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(45),
    [anon_sym_COMMA] = ACTIONS(45),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(45),
  },
  [STATE(26)] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_upper_ident] = ACTIONS(65),
    [anon_sym_I8] = ACTIONS(65),
    [anon_sym_U8] = ACTIONS(65),
    [anon_sym_I16] = ACTIONS(65),
    [anon_sym_U16] = ACTIONS(65),
    [anon_sym_I32] = ACTIONS(65),
    [anon_sym_U32] = ACTIONS(65),
    [anon_sym_I64] = ACTIONS(65),
    [anon_sym_U64] = ACTIONS(65),
    [anon_sym_I128] = ACTIONS(65),
    [anon_sym_U128] = ACTIONS(65),
    [anon_sym_F32] = ACTIONS(65),
    [anon_sym_F64] = ACTIONS(65),
    [anon_sym_Str] = ACTIONS(65),
    [anon_sym_Bool] = ACTIONS(65),
    [anon_sym_List] = ACTIONS(65),
    [anon_sym_Map] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_COMMA] = ACTIONS(63),
    [anon_sym_RBRACE] = ACTIONS(63),
    [anon_sym_LBRACK] = ACTIONS(63),
    [anon_sym_RBRACK] = ACTIONS(63),
  },
  [STATE(27)] = {
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_upper_ident] = ACTIONS(41),
    [anon_sym_I8] = ACTIONS(41),
    [anon_sym_U8] = ACTIONS(41),
    [anon_sym_I16] = ACTIONS(41),
    [anon_sym_U16] = ACTIONS(41),
    [anon_sym_I32] = ACTIONS(41),
    [anon_sym_U32] = ACTIONS(41),
    [anon_sym_I64] = ACTIONS(41),
    [anon_sym_U64] = ACTIONS(41),
    [anon_sym_I128] = ACTIONS(41),
    [anon_sym_U128] = ACTIONS(41),
    [anon_sym_F32] = ACTIONS(41),
    [anon_sym_F64] = ACTIONS(41),
    [anon_sym_Str] = ACTIONS(41),
    [anon_sym_Bool] = ACTIONS(41),
    [anon_sym_List] = ACTIONS(41),
    [anon_sym_Map] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(39),
  },
  [STATE(28)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [sym_upper_ident] = ACTIONS(91),
    [anon_sym_I8] = ACTIONS(91),
    [anon_sym_U8] = ACTIONS(91),
    [anon_sym_I16] = ACTIONS(91),
    [anon_sym_U16] = ACTIONS(91),
    [anon_sym_I32] = ACTIONS(91),
    [anon_sym_U32] = ACTIONS(91),
    [anon_sym_I64] = ACTIONS(91),
    [anon_sym_U64] = ACTIONS(91),
    [anon_sym_I128] = ACTIONS(91),
    [anon_sym_U128] = ACTIONS(91),
    [anon_sym_F32] = ACTIONS(91),
    [anon_sym_F64] = ACTIONS(91),
    [anon_sym_Str] = ACTIONS(91),
    [anon_sym_Bool] = ACTIONS(91),
    [anon_sym_List] = ACTIONS(91),
    [anon_sym_Map] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_COMMA] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 1,
      sym_upper_ident,
    STATE(29), 2,
      sym_type_definition,
      aux_sym_schema_repeat1,
  [11] = 3,
    ACTIONS(5), 1,
      sym_upper_ident,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    STATE(29), 2,
      sym_type_definition,
      aux_sym_schema_repeat1,
  [22] = 3,
    ACTIONS(100), 1,
      anon_sym_COMMA,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      aux_sym_record_type_repeat1,
  [32] = 3,
    ACTIONS(104), 1,
      anon_sym_COMMA,
    ACTIONS(106), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      aux_sym_tag_union_repeat1,
  [42] = 3,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      anon_sym_RBRACK,
    STATE(39), 1,
      aux_sym_tag_union_repeat1,
  [52] = 3,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    ACTIONS(114), 1,
      sym_lower_ident,
    STATE(37), 1,
      sym_record_field,
  [62] = 3,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      aux_sym_record_type_repeat1,
  [72] = 3,
    ACTIONS(114), 1,
      sym_lower_ident,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym_record_field,
  [82] = 3,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      aux_sym_record_type_repeat1,
  [92] = 3,
    ACTIONS(127), 1,
      sym_upper_ident,
    ACTIONS(129), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_tag_variant,
  [102] = 3,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RBRACK,
    STATE(39), 1,
      aux_sym_tag_union_repeat1,
  [112] = 3,
    ACTIONS(127), 1,
      sym_upper_ident,
    ACTIONS(136), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      sym_tag_variant,
  [122] = 3,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(114), 1,
      sym_lower_ident,
    STATE(45), 1,
      sym_record_field,
  [132] = 3,
    ACTIONS(110), 1,
      anon_sym_RBRACK,
    ACTIONS(127), 1,
      sym_upper_ident,
    STATE(46), 1,
      sym_tag_variant,
  [142] = 1,
    ACTIONS(138), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [147] = 1,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      sym_upper_ident,
  [152] = 1,
    ACTIONS(119), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [157] = 1,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [162] = 2,
    ACTIONS(142), 1,
      anon_sym_COLON,
    ACTIONS(144), 1,
      anon_sym_QMARK,
  [169] = 2,
    ACTIONS(114), 1,
      sym_lower_ident,
    STATE(45), 1,
      sym_record_field,
  [176] = 1,
    ACTIONS(146), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [181] = 2,
    ACTIONS(127), 1,
      sym_upper_ident,
    STATE(46), 1,
      sym_tag_variant,
  [188] = 1,
    ACTIONS(148), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [193] = 1,
    ACTIONS(150), 1,
      anon_sym_COLON,
  [197] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
  [201] = 1,
    ACTIONS(154), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(29)] = 0,
  [SMALL_STATE(30)] = 11,
  [SMALL_STATE(31)] = 22,
  [SMALL_STATE(32)] = 32,
  [SMALL_STATE(33)] = 42,
  [SMALL_STATE(34)] = 52,
  [SMALL_STATE(35)] = 62,
  [SMALL_STATE(36)] = 72,
  [SMALL_STATE(37)] = 82,
  [SMALL_STATE(38)] = 92,
  [SMALL_STATE(39)] = 102,
  [SMALL_STATE(40)] = 112,
  [SMALL_STATE(41)] = 122,
  [SMALL_STATE(42)] = 132,
  [SMALL_STATE(43)] = 142,
  [SMALL_STATE(44)] = 147,
  [SMALL_STATE(45)] = 152,
  [SMALL_STATE(46)] = 157,
  [SMALL_STATE(47)] = 162,
  [SMALL_STATE(48)] = 169,
  [SMALL_STATE(49)] = 176,
  [SMALL_STATE(50)] = 181,
  [SMALL_STATE(51)] = 188,
  [SMALL_STATE(52)] = 193,
  [SMALL_STATE(53)] = 197,
  [SMALL_STATE(54)] = 201,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_variant, 1, 0, 3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_union, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_union, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_type, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_type, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_type, 4, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_union, 4, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_union, 4, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_union, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_union, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 5, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_type, 5, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_union, 5, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_union, 5, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_reference, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_reference, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_type, 3, 0, 4),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map_type, 3, 0, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 2, 0, 2),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_type, 2, 0, 2),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 6, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_type, 6, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_union, 6, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_union, 6, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_union_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_union_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_field, 3, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 3, 0, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_field, 4, 0, 6),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_variant, 2, 0, 5),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_babylon(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_upper_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
